#define SE_LOC_TYPE_TOWN 0
#define SE_LOC_TYPE_BASE 1
#define SE_LOC_TYPE_POLICE_STATION 2
#define SE_LOC_TYPE_AIRPORT 3
#define SE_LOC_TYPE_MILITARY_HQ 4
#define SE_LOC_TYPE_PLAYER_CAMP 5
#define SE_LOC_TYPE_UNKNOWN 6